language: java
jdk:
- oraclejdk8
script: mvn install
deploy:
  provider: releases
  user: sfauvel
  api_key: qJ1JKR4X0E+8AQndVZZvz9WN0ang087sVomWiJxtAp0zEOxqfPV6ZEwDzHLHEBlfsh5w75VOYdPnVkkJC5xOmgwQMFOpnlTZlkVADTq9Fp9X9eheDi5d1jr7+6gYWAwOF19RLvLZF2nrRhI0WEBdue4wZLasDKDcenMvqA4wx7URe1UO6INtapV4fsPUKSDgqEqc+xp0Q5sroM36IPvKO6W+FLIZvkCBOxFQIpGp3q0WWoMLXiF4N6S2hC6CQw1NmtCW8cfXuVnn6lTr9lO2EUmXgG03KJS13VWcVyYuA47EiEn2hpo3xrG0AB9WunJDcxpAzuvsakVxVOk5ZTv0y2N+gqQR+6V8Xqee/xgebbLCxn3cZYc0GS5abWvYRCpMdPaFVHPhhZXyqz5rTr/tp7LvvVUY/nBJMBFKcm2FSSaC4cBIo2gl5smjUHUZ0QshUWgBOeElyIB9J1/35K0eFVoFRjlZGTzua77u71um4mDcXnYfQ+iuQ5AcOKgalxKqFQpqo9A5n+q2w8GKwjJJ9aGxCThr31ft6SJJuztWdCyrU1B+WW0h6e0M7c8MZXCo9tVSP9PvN9Fcj0HiAPd6qGjrdlvzrX1LDyhFdMH9vrWD6whTVO4t75plsiFmsJ1YPw/T6j/z0Cgm+uHXdHlFSJjbxrdkvkafNPXr3gUC280=
  file: target/once-core-0.0.9.2.jar
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
    - sfauvel@gmail.com
    on_success: change
    on_failure: always
