language: java
script: mvn install
deploy:
  provider: releases
  user: sfauvel
  file: target/once-core-0.0.9.2.jar
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: SqfPTghlKQVj/xCDdjkFUZfaKWoviOLEDRKRxjYX8lFO42OLDyuwq4myGM6Gf5Wva+tip/BRfXI1cqxITJ83MgqxgYWMDIUASAy7GNWfPmObT/vjOGOc0BzVHrBdhdlrqkSVL4iHj2H+dMq2a9UAciaeRsVDipPE4u5dtjvpW+0dBv+9ciJRp8Z0mtIPGHh7G6PTXlYfXfpJRkPayCwOntvA6ZKMuYL5Q1PsLOs+9qcMoGgxyeMqe5Ea3KThB789mZf/vGSp8Gr3lzIiOfThDzgZNrE+dI9i1l8oI/1KS/ZugedZEdYU5+yu5aHirl+Z34IJNCRfh7xnq8AEIoJc+JgNf7ADuOxCAEYrPJzcqVBJJvw9whfCiBKoiJnlcvkF63pouJ6bLoQUq/iPZZYRy9vWzXTAlpru19NXhMd1uFuTtrHSCytMEKX87zlLq/qLA1gSBrwZ5RbFT0q6BTvHVfZx2E6X1J9yfS7epw0i1VkyAk6ThNBgqL6quDIXmeUoN7P6CeZ1nERDCdNeXcjDFNUFYGHDgzvA17etyS7qzu04/aU6VBZu4w5Gml0yiKSiG8K6g+1efjHTSGaKN2Q/x7iNzk4AOgOn9FuwVKRH0L48OvLl26FssFebfuwV+YHSNwSSGiP8uiNA7Gf7MSjmWmmmjEN2Z8AzCLSaStm9vpE=
