language: java
script: mvn install
deploy:
  provider: releases
  user: sfauvel
  file: target/once-core-0.0.9.2.jar
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: "kwSald2lhUZkrJT1smXNyGNI+vrwF1UYbxE7SU/QpvX8M3icg53UfaEI4twW9RgiTgr0t7L6/119QBBTtHO6RfP8pd5qfr7abAs5NXzi26aCMSRibgBJJWv3XDfghYmIKYMK9dhY7qe+RuEVpPNBTj2LJF3Yh9hlfQ0/6Y8iEKLG0jmZnOlcy9DaZru0AonCjLhUrqE4OsQpER67MimD39OgWfgi122eoQxCGTwA5vUd0BpE7l2bWEEQlFrAZIRL+E86F10GBJwh013KGlfzEYEfKBXnp+14aFw6OpLFX2+9r1vLvUzrRFT62Qbf7fYkGtYKGX+5rrZF7e+qmKs1kjIhTmXVa6s29EG99jpSjm2lwFD5WM0d0I/vOBauo4B+AfnMXC5RyWCye8Q/cHRwftkMuFBOxFxP9R7hI7ihwLKWQC7tMpPGW4QM920d4k3P8Bnxb+HsIImrqOJJkU80jCi/4tZPnK21BnH3kyn+Ew0de8cOaMW/0W72Xrt5Pnp2eBgy93ryYe9N6YTY3lxmPzDW48e1lOqIezAcYBKMyyKz7doJbSyCwrrROwDVM19bBeL+ys76TLf3M8Yfy8kBo3L4pLWu3IHvpGM2+DMS7+LL3Eu1/+JoWBoTEe++h33TGt0saiYEFHsfY9llyTGJe3W8ybjk9zV7IkuEep9Hk4c="