language: java
jdk:
- oraclejdk8
script: mvn install
deploy:
  provider: releases
  user: sfauvel
  api_key:
    secure: p4fdOZa0g/SxmAQ2Ny95oXnhjOcdNi3D9ODwMp+66hsNCstdmM/qYbVq/HkWP2lh8mNnbnXC8oLiyUeh/5kwNtkF16ZoboFq+FbhuygRHQZL9lA9EH7hJLegHZqAO/ffHVA7RoYZ9Duuh5DGZvRtlxD7DoLFYVJ7uoKFjqITuDwbXXxp6CpQp3gZ1SlR+hW4coVf69H+L09vwACb2dSCt/ETW/xiyTfzPh2HMP21sVFIeQ+dwelSJgh6l2imqRCeZFiMshA9wExZESJRx9vgGRRHdKf7sxWWE8xmQpOdFVZuOShACFm4hCBJRZj3yhCe4pvPLDyL5jEkX0KN4Pb9VMLGGWaoZX7+LzystrQVqPKfbWtUBXgTYwnxMd+xYHw62lFqnwM3dvNh7Jb8x0zmUUEZTTag01sNXvabQgL6H8lamlFJo9FBCw+CsLHfgxdqjciLzasbF9iQ+nsBm1HEVxesVL1xXgccoXtfLAUKBohUGDB8L7L/impssuWwBoB/Zr5LsXkWvZkIMVw5EKCxp0yKEBspjGVSuboHmz4kvR+xAwgZ0DdyoZtdRmd7eMHwUFvThBF+3zR40rB6lDGRTNjTNd3xXDeOGh56q7UsYS7QrMUY0XaJ4FCkQ5ThfrWZWeXLZbmMFEWXRYkMsUiorF3mLApM+oykUoo7wjDOgYA=
  file: target/once-0.0.9.2-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
    - sfauvel@gmail.com
    on_success: change
    on_failure: always
