# Once: detect duplication in source code
language: java

# Commande Maven executée par défaut
script: mvn test

# Deploy
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: target/once-core-0.0.9.2-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    tags: true